language: objective-c
xcode_project: vimman-ios.xcodeproj
xcode_scheme: vimman-iosTests
before_install:
  - sudo easy_install cpp-coveralls
  - brew uninstall xctool
  - brew update
  - brew install xctool --HEAD 
script:
  - make test
  - xctool test ONLY_ACTIVE_ARCH=NO GCC_INSTRUMENT_PROGRAM_FLOW_ARCS=YES GCC_GENERATE_TEST_COVERAGE_FILES=YES
after_success:
  - ./script/coveralls.sh
notifications:
  email:
    recipients: tetsuwo.oishi@gmail.com
    on_success: always # [always|never|change]
    on_failure: always # [always|never|change]
